# coding=utf-8
from __future__ import unicode_literals
from ..address import Provider as AddressProvider


class Provider(AddressProvider):
    street_suffixes_short = ['ul.', 'al.']
    street_address_formats = ['{{street_name}} {{building_number}}', ]
    address_formats = ['{{street_address}}\n{{postcode}} {{city}}', ]
    building_number_formats = ['###', '##', '#', '#/#']


    cities = (
        'Warszawa',
        'Kraków',
        'Łódź',
        'Wrocław',
        'Poznań',
        'Gdańsk',
        'Szczecin',
        'Bydgoszcz',
        'Lublin',
        'Katowice',
        'Białystok',
        'Gdynia',
        'Częstochowa',
        'Radom',
        'Sosnowiec',
        'Toruń',
        'Kielce',
        'Gliwice',
        'Rzeszów',
        'Zabrze',
        'Bytom',
        'Olsztyn',
        'Bielsko-Biała',
        'Ruda Śląska',
        'Rybnik',
        'Tychy',
        'Dąbrowa Górnicza',
        'Gorzów Wielkopolski',
        'Elbląg',
        'Płock',
        'Opole',
        'Wałbrzych',
        'Zielona Góra',
        'Włocławek',
        'Tarnów',
        'Chorzów',
        'Koszalin',
        'Kalisz',
        'Legnica',
        'Grudziądz',
        'Słupsk',
        'Jaworzno',
        'Jastrzębie-Zdrój',
        'Nowy Sącz',
        'Jelenia Góra',
        'Konin',
        'Piotrków Trybunalski',
        'Siedlce',
        'Inowrocław',
        'Mysłowice',
        'Piła',
        'Lubin',
        'Ostrów Wielkopolski',
        'Ostrowiec Świętokrzyski',
        'Gniezno',
        'Stargard Szczeciński',
        'Siemianowice Śląskie',
        'Suwałki',
        'Głogów',
        'Pabianice',
        'Chełm',
        'Zamość',
        'Tomaszów Mazowiecki',
        'Leszno',
        'Przemyśl',
        'Stalowa Wola',
        'Kędzierzyn-Koźle',
        'Łomża',
        'Żory',
        'Mielec',
        'Tarnowskie Góry',
        'Tczew',
        'Bełchatów',
        'Świdnica',
        'Ełk',
        'Pruszków',
        'Będzin',
        'Biała Podlaska',
        'Zgierz',
        'Piekary Śląskie',
        'Racibórz',
        'Legionowo',
        'Ostrołęka',
        'Świętochłowice',
        'Starachowice',
        'Zawiercie',
        'Wejherowo',
        'Puławy',
        'Wodzisław Śląski',
        'Starogard Gdański',
        'Skierniewice',
        'Tarnobrzeg',
        'Skarżysko-Kamienna',
        'Radomsko',
        'Krosno',
        'Rumia',
        'Dębica',
        'Kołobrzeg',
        'Kutno',
        'Nysa',
        'Ciechanów',
        'Otwock',
        'Piaseczno',
        'Zduńska Wola',
        'Sieradz',
        'Świnoujście',
        'Żyrardów',
        'Szczecinek',
        'Świdnik',
        'Chojnice',
        'Nowa Sól',
        'Oświęcim',
        'Bolesławiec',
        'Mińsk Mazowiecki',
        'Mikołów',
        'Jarosław',
        'Sanok',
        'Knurów',
        'Malbork',
        'Żary',
        'Kwidzyn',
        'Chrzanów',
        'Sopot',
        'Sochaczew',
        'Wołomin',
        'Oleśnica',
        'Brzeg',
        'Olkusz',
        'Jasło',
        'Cieszyn',
        'Kraśnik',
        'Lębork',
        'Czechowice-Dziedzice',
        'Dzierżoniów',
        'Ostróda',
        'Police',
        'Nowy Targ',
        'Iława',
        'Czeladź',
        'Myszków',
        'Żywiec',
        'Zgorzelec',
        'Oława',
        'Bielawa',
        'Swarzędz',
        'Mława',
        'Ząbki',
        'Łuków',
        'Augustów',
        'Śrem',
        'Bochnia',
        'Luboń',
        'Giżycko',
        'Grodzisk Mazowiecki',
        'Łowicz',
        'Krotoszyn',
        'Września',
        'Turek',
        'Pruszcz Gdański',
        'Brodnica',
        'Gorlice',
        'Czerwionka-Leszczyny',
        'Kłodzko',
        'Marki',
        'Nowy Dwór Mazowiecki',
        'Kętrzyn',
        'Zakopane',
        'Wyszków',
        'Biłgoraj',
        'Żagań',
        'Bielsk Podlaski',
        'Świecie',
        'Wałcz',
        'Jarocin',
        'Pszczyna',
        'Wągrowiec',
        'Szczytno',
        'Białogard',
        'Sandomierz',
        'Bartoszyce',
        'Kluczbork',
        'Lubliniec',
        'Skawina',
        'Jawor',
        'Kościan',
        'Wieluń',
        'Kościerzyna',
        'Nowa Ruda',
        'Świebodzice',
        'Koło',
        'Piastów',
        'Goleniów',
        'Ostrów Mazowiecka',
        'Polkowice',
        'Lubartów',
        'Zambrów',
        'Płońsk',
        'Reda',
        'Łaziska Górne',
        'Środa Wielkopolska'
    )

    streets = (
        'Polna',
        'Leśna',
        'Słoneczna',
        'Krótka',
        'Szkolna',
        'Ogrodowa',
        'Lipowa',
        'Brzozowa',
        'Łąkowa',
        'Kwiatowa',
        'Sosnowa',
        'Kościelna',
        'Akacjowa',
        'Parkowa',
        'Zielona',
        'Kolejowa',
        'Sportowa',
        'Dębowa',
        'Kościuszki',
        'Maja',
        'Mickiewicza',
        'Cicha',
        'Spokojna',
        'Klonowa',
        'Spacerowa',
        'Swierkowa',
        'Kasztanowa',
        'Nowa',
        'Piaskowa',
        'Sienkiewicza',
        'Rózana',
        'Topolowa',
        'Wisniowa',
        'Dworcowa',
        'Wiejska',
        'Graniczna',
        'Słowackiego',
        'Długa',
        'Wrzosowa',
        'Konopnickiej',
        'Boczna',
        'Wąska',
        'Wierzbowa',
        'Jaśminowa',
        'Wspólna',
        'Modrzewiowa',
        'Kopernika',
        'Jana Pawla II',
        'Poprzeczna',
        'Wesola',
        'Pogodna',
        'Zeromskiego',
        'Rynek',
        'Bukowa',
        'Wojska Polskiego',
        'Sadowa',
        'Górna',
        'Jodłowa',
        'Wolnosci',
        'Glówna',
        'Mlynska',
        'Strażacka',
        'Prusa',
        'Jesionowa',
        'Przemysłowa',
        'Osiedlowa',
        'Wiosenna',
        'Sikorskiego',
        'Chopina',
        'Poludniowa',
        'Malinowa',
        'Stawowa',
        'Reymonta',
        'Piłsudskiego',
        'Zacisze',
        'Cmentarna',
        'Okrężna',
        'Kochanowskiego',
        'Armii Krajowej',
        'Mila',
        'Jasna',
        'Wodna',
        'Zamkowa',
        'Witosa',
        'Reja',
        'Warszawska',
        'Miodowa',
        'Partyzantów',
        'Krzywa',
        'Kilińskiego',
        'Dolna',
        'Podgórna',
        'Kręta',
        'Jarzebinowa',
        'Moniuszki',
        'Targowa',
        'Prosta',
        'Orzeszkowej',
        'Spółdzielcza',
        'Jagodowa',
        'Działkowa',
        'Staszica',
        'Orzechowa',
        'Rzemieślnicza',
        'Rzeczna',
        'Boleslawa Chrobrego',
        'Fabryczna',
        'Teczowa',
        'Chabrowa',
        'Poziomkowa',
        'Konwaliowa',
        'Wyszynskiego',
        'Kalinowa',
        'Północna',
        'Matejki',
        'Grunwaldzka',
        'Cisowa',
        'Nadrzeczna',
        'Pocztowa',
        'Zachodnia',
        'Dąbrowskiego',
        'Grabowa',
        'Norwida',
        'Źródlana',
        'Asnyka',
        'Gajowa',
        'Paderewskiego',
        'Listopada',
        'Wyspiańskiego',
        'Mostowa',
        'Broniewskiego',
        'Tuwima',
        'Wschodnia',
        'Jaworowa',
        'Poznanska',
        'Makowa',
        'Bema',
        'Jeziorna',
        'Piękna',
        'Czereśniowa',
        'Mała',
        'Krakowska',
        'Radosna',
        'Leszczynowa',
        'Traugutta',
        'Jadwigi',
        'Rolna',
        'Wyzwolenia',
        'Piastowska',
        'Grzybowa',
        'Krasickiego',
        'Podlesna',
        'Żytnia',
        'Złota',
        'Bursztynowa',
        'Żwirowa',
        'Stycznia',
        'Widokowa',
        'Kazimierza Wielkiego',
        'Kamienna',
        'Jalowcowa',
        'Morelowa',
        'Mieszka I',
        'Myśliwska',
        'Łączna',
        'Szpitalna',
        'Wczasowa',
        'Zurawia',
        'Fiolkowa',
        'Glowackiego',
        'Rolnicza',
        'Tulipanowa',
        'Wladyslawa Jagielly',
        'Dworska',
        'Letnia',
        'Liliowa',
        'Owocowa',
        'Pułaskiego',
        'Stefana Batorego',
        'Harcerska',
        'Kołłątaja',
        'Strzelecka',
        'Kraszewskiego',
        'Wladyslawa Lokietka',
        'Żwirki i Wigury',
        'Wrocławska',
        'Gdańska',
        'Turystyczna',
        'Niepodległości',
        'Poniatowskiego',
        'Korczaka',
        'Rybacka',
        'Narutowicza',
        'Okrzei',
        'Krucza',
        'Jagiellonska',
        'Swierczewskiego',
        'Kasprowicza',
        'Szeroka',
        'Jana III Sobieskiego',
        'Mlynarska',
        'Olchowa',
        'Powstanców Slaskich',
        'Rumiankowa',
        'Stroma',
        'Starowiejska',
        'Mazowiecka',
        'Lawendowa',
        'Robotnicza',
        'Zbozowa',
        'Mokra',
        'Powstanców Wielkopolskich',
        'Towarowa',
        'Dobra',
        'Środkowa',
        'Willowa',
        'Zielna',
        'Zdrojowa',
        'Opolska',
        'Agrestowa',
        'Księżycowa',
        'Zwycięstwa',
        'Fredry',
        'Letniskowa',
        'Andersa',
        'Baczyńskiego',
        'Batalionów Chłopskich',
        'Dąbrowskiej',
        'Orla',
        'Sklodowskiej-Curie',
        'Blekitna',
        'Rubinowa',
        'Brzoskwiniowa',
        'Urocza',
        'Galczynskiego',
        'Krasinskiego',
        'Pomorska',
        'Szymanowskiego',
        'Jeżynowa',
        'Czarnieckiego',
        'Nałkowskiej',
        'Zaciszna',
        'Porzeczkowa',
        'Krańcowa',
        'Jesienna',
        'Klasztorna',
        'Irysowa',
        'Niecała',
        'Wybickiego',
        'Nadbrzeżna',
        'Szarych Szeregów',
        'Wałowa',
        'Słowicza',
        'Strumykowa',
        'Drzymały',
        'Gołębia',
        'Torowa',
        'Cegielniana',
        'Cyprysowa',
        'Słowianska',
        'Diamentowa',
        'Waryńskiego',
        'Częstochowska',
        'Dojazdowa',
        'Przechodnia',
        'Hallera',
        'Lubelska',
        'Plater',
        'Popieluszki',
        'Borówkowa',
        'Chełmońskiego',
        'Daszynskiego',
        'Plażowa',
        'Tartaczna',
        'Jabłoniowa',
        'Kossaka',
        'Skargi',
        'Ludowa',
        'Sokola',
        'Azaliowa',
        'Szmaragdowa',
        'Lipca',
        'Staffa',
        'Tysiąclecia',
        'Brzechwy',
        'Jastrzębia',
        'Kusocińskiego',
        'Storczykowa',
        'Wilcza',
        'Górnicza',
        'Szafirowa',
        'Dlugosza',
        'Handlowa',
        'Krokusowa',
        'Skladowa',
        'Widok',
        'Perlowa',
        'Skosna',
        'Wypoczynkowa',
        'Chmielna',
        'Jaskólcza',
        'Nowowiejska',
        'Piwna',
        'Slaska',
        'Zaulek',
        'Glogowa',
        'Górska',
        'Truskawkowa',
        'Kaszubska',
        'Kosynierów',
        'Mazurska',
        'Srebrna',
        'Bociania',
        'Ptasia',
        'Cedrowa',
        'Rycerska',
        'Wieniawskiego',
        'Zabia',
        'Torunska',
        'Podmiejska',
        'Słonecznikowa',
        'Sowia',
        'Stolarska',
        'Powstanców',
        'Sucharskiego',
        'Boleslawa Krzywoustego',
        'Konarskiego',
        'Szczesliwa',
        'Lazurowa',
        'Miarki',
        'Narcyzowa',
        'Browarna',
        'Konstytucji 3 Maja',
        'Majowa',
        'Milosza',
        'Malczewskiego',
        'Orkana',
        'Skrajna',
        'Bankowa',
        'Bydgoska',
        'Piekarska',
        'Zeglarska',
        'Jana',
        'Turkusowa',
        'Tylna',
        'Wysoka',
        'Zakątek',
        'Maczka',
        'Morska',
        'Rataja',
        'Szewska',
        'Podwale',
        'Pałacowa',
        'Magnoliowa',
        'Ceglana',
        'Sawickiej',
        'Sciegiennego',
        'Wiklinowa',
        'Zakole',
        'Borowa',
        'Kolorowa',
        'Lisia',
        'Lotnicza',
        'Sarnia',
        'Wiązowa',
        'Grottgera',
        'Kolonia',
        'Królewska',
        'Promienna',
        'Daleka',
        'Jana Sobieskiego',
        'Rejtana',
        'Wiatraczna',
        'Kaliska',
        'Lanowa',
        'Srednia',
        'Wislana',
        'Wróblewskiego',
        'Koralowa',
        'Kruczkowskiego',
        'Lelewela',
        'Makuszynskiego',
        'Sybiraków',
        'Kowalska',
        'Morcinka',
        'Odrzanska',
        'Okulickiego',
        'Solidarnosci',
        'Zapolskiej',
        'Labedzia',
        'Wojciecha',
        'Baltycka',
        'Lwowska',
        'Rajska',
        'Korfantego',
        'Pszenna',
        'Ciasna',
        'Floriana',
        'Hutnicza',
        'Kielecka'
    )

    postcode_formats = ('##-###',)

    @classmethod
    def street_name(cls):
        suffix = cls.random_element(cls.street_suffixes_short)
        return suffix + ' ' + cls.random_element(cls.streets)

    @classmethod
    def city(cls):
        return cls.random_element(cls.cities)